[package]
name = "basicb"
version = "0.1.0"
authors = ["Jack Wrenn <me@jswrenn.com>"]
description = "Beep the PC speaker"
license = "MIT"

[dependencies]
beep = "0.2"
structopt = "0.2"
dimensioned = "0.6"